### ISSUE TITLE
yarn test error

### ISSUE THREAD

**Issue by nicolas-lukita** [nicolas-lukita/tacker-backend#3]
Error when running test or start if dependencies installed using yarn install:

`Error [ERR_REQUIRE_ESM]: require() of ES Module ./tacker-backend/node_modules/string-width/index.js from ./tacker-backend/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in ./tacker-backend/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.`

Works fine if dependencies installed using npm install.

**Comment by hanstanawi** [comment]
Fixed by updating jest dependencies
